# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.25
# 

Name:       nodejs

# >> macros
# << macros

Summary:    Evented I/O for V8 JavaScript
Version:    0.10.2
Release:    1
Group:      Development/Languages
License:    MIT
URL:        http://www.nodejs.org
Source0:    %{name}.tar.gz
Source100:  nodejs.yaml
BuildRequires:  pkgconfig(openssl)
BuildRequires:  pkgconfig(zlib)
BuildRequires:  curl
BuildRequires:  gcc-c++
BuildRequires:  procps
BuildRequires:  pkgconfig
BuildRequires:  python
Provides:   npm = %{version}

%description
Provides an easy way to build scalable network programs
http://nodejs.org



%prep
%setup -q -n src

# >> setup
# << setup

%build
# >> build pre
export CFLAGS="%{optflags}"
export CXXFLAGS="%{optflags}"
#./configure --prefix=%{_prefix} --shared-v8 --shared-openssl --shared-zlib --gdb
./configure --prefix=%{_prefix} --shared-openssl --shared-zlib --gdb
# << build pre


make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
#node-gyp needs common.gypi too
mkdir -p %{buildroot}%{_datadir}/node
cp -p common.gypi %{buildroot}%{_datadir}/node

# << install post


%files
%defattr(-,root,root,-)
%{_bindir}/node
%{_mandir}/*/*
%{_libdir}/dtrace
%{_datadir}/node
%doc AUTHORS LICENSE
%{_libdir}/node_modules
%exclude %{_libdir}/node_modules/npm/.npmignore
%attr(755,root,root) %{_bindir}/npm
%exclude %{_libdir}/node_modules/npm/scripts/clean-old.sh
%exclude %{_libdir}/node_modules/npm/scripts/install.sh
%attr(755,root,root) %{_libdir}/node_modules/npm/scripts/clean-old.sh
%attr(755,root,root) %{_libdir}/node_modules/npm/scripts/install.sh
# >> files
# << files
